### ISSUE TITLE
No Gender avaiable

### ISSUE THREAD

**Issue by duramson** [diowa/icare#1172]
The Code suggest, that you can choose your Gender and also create "Pink Itineraries".
However i cant find a possibility to choose your gender in the Profile page.

**Comment by tagliala** [comment]
Hi!

Thanks, yes, I can confirm this is an issue.

It happened when switching from Facebook to Auth0: #371

Since:
- Auth0 does not offer this field by default (for a good reason IMHO)
- I want to keep the personal data at the bare minimum in the open source code
- Anyone can create two accounts with different genders
- Setting the gender on the application itself should be throttled or limited

I think that this feature should be either removed or rethought to something different

Maybe it is a good chance to remove it from the core, but feel free to implement it by adding the missing field in your fork and it should work with the existing code, it is even tested :)

**Comment by duramson** [comment]
Hey and thanks for the fast reply. I was editing my issue while a got your answer :)

So i could add a gender field in Auth0 like the Name and it should work again? Also found no way to add/edit a bio.
There is no way to leave feedback.  It seems that there a lot of functions in the code but not rendered in HTML.

Anyway thanks for this Project. I'm working on a science project and will provide a german translation when i'm done.

**Comment by tagliala** [comment]
Hi, thanks for your interest in this project

> So i could add a gender field in Auth0 like the Name and it should work again?

It seems to be possible to add a dropdown selection of fields https://community.auth0.com/t/customize-universal-login-lock-with-additionalsignupfields/35905/2

I did something for the name and it's documented in the wiki at https://github.com/diowa/icare/wiki/Setup-Auth0-App#add-name-to-sign-up-form

> Also found no way to add/edit a bio.

Yes, most of those information was taken from Facebook and now it is not available anymore

I think that adding back fields to the user is slightly out of the scope of this demo. We just wanted to demonstrate that it is possible to get data from a third-party authentication system easily

Said so, since this is a pretty standard Rails application, it is possible to add fields and logic on those fields if needed in a fork of this project

> I'm working on a science project and will provide a german translation when i'm done.

Yes, thanks, I would appreciate that
