### ISSUE TITLE
Deployment on a Linux server

### ISSUE THREAD

**Issue by ZiadJ** [diowa/icare#31]
Hi,
First I'd like to thank you for sharing your code to the community. It's a fantastic project that deserves more attention. However I'd prefer to deploy it on my existing Linux server so I don't have to rely on the Heroku infrastructure. Is this an option in its current state?

**Comment by tagliala** [comment]
@ZiadJ thanks!

Sure it is, and feel free to write a wiki on that topic.

We have an out to date wiki on how to set up a development environment on linux: https://github.com/diowa/icare/wiki/%5BW.I.P.%5D-Developing-icare-on-ubuntu-12.10

Since icare is a RoR application, you can use any internet resource on how setting up a server with Ruby on Rails and deploys with Capistrano

Here there are some resources that might be useful
https://gorails.com/deploy/ubuntu/14.04
http://code.tutsplus.com/tutorials/setting-up-a-rails-server-and-deploying-with-capistrano-on-fedora-from-scratch--net-10443 (maybe a little bit old)
http://www.gotealeaf.com/blog/deploy-rails-apps-with-capistrano

You also need mongodb installed: http://docs.mongodb.org/manual/tutorial/install-mongodb-on-linux/
